image:
  file: .docker/gitpod/Dockerfile

vscode:
  extensions:
    - leanprover.lean4

tasks:
  - init: |
      lake exe cache get && lake build Library.Tactic.Exhaust
    command: |
      PATH="$PATH:/workspace/math2001/scripts"