image:
  file: .docker/gitpod/Dockerfile

vscode:
  extensions:
    - leanprover.lean4
    - usernamehw.errorlens

tasks:
  - init: |
      lake exe cache get
    command: |
      PATH="$PATH:/workspace/math2001/scripts"